# Generated by Django 5.2.5 on 2025-08-11 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FundBasicInfo',
            fields=[
                ('fund_id', models.AutoField(primary_key=True, serialize=False)),
                ('fund_code', models.CharField(max_length=20, unique=True)),
                ('fund_name', models.CharField(max_length=200)),
                ('fund_type', models.CharField(max_length=50)),
                ('currency', models.CharField(default='CNY', max_length=10)),
                ('listing_exchange', models.CharField(max_length=100)),
                ('fund_company', models.CharField(max_length=100)),
                ('inception_date', models.DateField()),
                ('index_tracked', models.CharField(blank=True, max_length=200, null=True)),
                ('management_fee', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('custodian_fee', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FundDailyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('opening_price', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('closing_price', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('highest_price', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('lowest_price', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('net_asset_value', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('estimated_nav', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.fundbasicinfo')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('fund', 'date')},
            },
        ),
    ]
