# Generated by Django 5.2.5 on 2026-03-28 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='funddailydata',
            old_name='closing_price',
            new_name='close',
        ),
        migrations.RenameField(
            model_name='funddailydata',
            old_name='highest_price',
            new_name='high',
        ),
        migrations.RenameField(
            model_name='funddailydata',
            old_name='lowest_price',
            new_name='low',
        ),
        migrations.RenameField(
            model_name='funddailydata',
            old_name='opening_price',
            new_name='open',
        ),
        migrations.AddField(
            model_name='funddailydata',
            name='volume',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
