# Generated by Django 5.2.5 on 2026-05-13 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_rename_closing_price_funddailydata_close_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundbasicinfo',
            name='market_timezone',
            field=models.CharField(default='America/New_York', max_length=64),
        ),
    ]
